#include "Functions.h"

using namespace OpenBlack::Script;

/*
* Function pointers for map.txt
*/
const Functions::FunctionPointer Functions::kMapFunctionPointers[] = {	
	{ 0,   "SET_NO_PLAYERS",       { kTypeNumber },                                        &Functions::setNoPlayers },
	{ 1,   "LOAD_TRIBE_DANCE",     { kTypeVector, kTypeNumber },                           &Functions::loadTribeDance },
	{ 2,   "SET_DATE",             { kTypeNumber, kTypeNumber, kTypeNumber },              &Functions::setDate },
	{ 3,   "SET_TIME",             { kTypeNumber, kTypeNumber, kTypeNumber },              &Functions::setTime },
	{ 4,   "SET_TURNS_PER_YEAR",   { kTypeNumber },                                        &Functions::setTurnsPerYear },
	{ 5,   "SET_GAME_TICK_TIME",   { kTypeNumber },                                        &Functions::setGameTickTime },
	{ 6,   "LOAD_FEATURE_SCRIPT",  { kTypeVector },                                        &Functions::loadFeatureScript },
	{ 7,   "PAUSE_GAME",           {  },                                                   &Functions::pauseGame },
	{ 8,   "CREATE_CREATURE",      { kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber }, &Functions::createCreature },
	{ 9,   "OUTPUT_VILLAGERS",     {  },                                                   &Functions::outputVillagers },
	{ 10,  "OUTPUT_TOWN",          {  },                                                   &Functions::outputTown },
	{ 11,  "OUTPUT_CREATURES",     {  },                                                   &Functions::outputCreatures },
	{ 12,  "OUTPUT_COLLIDE",       {  },                                                   &Functions::outputCollide },
	{ 13,  "OUTPUT_ALLOC",         {  },                                                   &Functions::outputAlloc },
	{ 14,  "SAVE_FOR_NET_DEBUG",   { kTypeNumber, kTypeNumber },                           &Functions::saveForNetDebug },
	{ 15,  "LOAD_FOR_NET_DEBUG",   { kTypeNumber },                                        &Functions::loadForNetDebug },
	{ 16,  "LOAD_LANDSCAPE",       { kTypeVector },                                        &Functions::loadLandscape },
	{ 17,  "LOAD_GAME_SCRIPT",     { kTypeVector },                                        &Functions::loadGameScript },
	{ 18,  "LOAD_RAW_GAME_SCRIPT", { kTypeVector },                                        &Functions::loadRawGameScript },
	{ 19,  "LOAD_LANGUAGE",        {  },                                                   &Functions::loadLanguage },
};

/*
* Function pointers for land scripts. (Land*.txt, Playgrounds/*.txt, etc..).
*/
const Functions::FunctionPointer Functions::kLandFunctionPointers[] = {
	{ 0,   "CREATE_MIST",                       { kTypeVector, kTypeFloat, kTypeNumber, kTypeFloat, kTypeFloat },                                                      &Functions::createMist },
	{ 1,   "CREATE_PATH",                       { kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                                                &Functions::createPath },
	{ 2,   "CREATE_TOWN",                       { kTypeNumber, kTypeVector, kTypeString, kTypeNumber, kTypeString },                                                   &Functions::createTown },
	{ 3,   "SET_TOWN_BELIEF",                   { kTypeNumber, kTypeString, kTypeFloat },                                                                              &Functions::setTownBelief },
	{ 4,   "SET_TOWN_BELIEF_CAP",               { kTypeNumber, kTypeString, kTypeFloat },                                                                              &Functions::setTownBeliefCap },
	{ 5,   "SET_TOWN_UNINHABITABLE",            { kTypeNumber },                                                                                                       &Functions::setTownUninhabitable },
	{ 6,   "SET_TOWN_CONGREGATION_POS",         { kTypeNumber, kTypeVector },                                                                                          &Functions::setTownCongregationPos },
	{ 7,   "CREATE_ABODE",                      { kTypeNumber, kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                         &Functions::createAbode },
	{ 8,   "CREATE_PLANNED_ABODE",              { kTypeNumber, kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                         &Functions::createPlannedAbode },
	{ 9,   "CREATE_TOWN_CENTRE",                { kTypeNumber, kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber },                                      &Functions::createTownCentre },
	{ 10,  "CREATE_TOWN_SPELL",                 { kTypeNumber, kTypeString },                                                                                          &Functions::createTownSpell },
	{ 11,  "CREATE_NEW_TOWN_SPELL",             { kTypeNumber, kTypeString },                                                                                          &Functions::createNewTownSpell },
	{ 12,  "CREATE_TOWN_CENTRE_SPELL_ICON",     { kTypeNumber, kTypeString },                                                                                          &Functions::createTownCentreSpellIcon },
	{ 13,  "CREATE_SPELL_ICON",                 { kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createSpellIcon },
	{ 14,  "CREATE_PLANNED_SPELL_ICON",         { kTypeNumber, kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber },                                      &Functions::createPlannedSpellIcon },
	{ 15,  "CREATE_VILLAGER",                   { kTypeVector, kTypeVector, kTypeString },                                                                             &Functions::createVillager },
	{ 16,  "CREATE_TOWN_VILLAGER",              { kTypeNumber, kTypeVector, kTypeVector, kTypeNumber },                                                                &Functions::createTownVillager },
	{ 17,  "CREATE_SPECIAL_TOWN_VILLAGER",      { kTypeNumber, kTypeVector, kTypeNumber, kTypeNumber },                                                                &Functions::createSpecialTownVillager },
	{ 18,  "CREATE_VILLAGER_POS",               { kTypeVector, kTypeVector, kTypeString, kTypeNumber },                                                                &Functions::createVillagerPos },
	{ 19,  "CREATE_CITADEL",                    { kTypeVector, kTypeNumber, kTypeString, kTypeNumber, kTypeNumber },                                                   &Functions::createCitadel },
	{ 20,  "CREATE_PLANNED_CITADEL",            { kTypeNumber, kTypeVector, kTypeNumber, kTypeString, kTypeNumber, kTypeNumber },                                      &Functions::createPlannedCitadel },
	{ 21,  "CREATE_CREATURE_PEN",               { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                      &Functions::createCreaturePen },
	{ 22,  "CREATE_WORSHIP_SITE",               { kTypeVector, kTypeNumber, kTypeString, kTypeString, kTypeNumber, kTypeNumber },                                      &Functions::createWorshipSite },
	{ 23,  "CREATE_PLANNED_WORSHIP_SITE",       { kTypeVector, kTypeNumber, kTypeString, kTypeString, kTypeNumber, kTypeNumber },                                      &Functions::createPlannedWorshipSite },
	{ 24,  "CREATE_ANIMAL",                     { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                                                &Functions::createAnimal },
	{ 25,  "CREATE_NEW_ANIMAL",                 { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createNewAnimal },
	{ 26,  "CREATE_FOREST",                     { kTypeNumber, kTypeVector },                                                                                          &Functions::createForest },
	{ 27,  "CREATE_TREE",                       { kTypeNumber, kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createTree },
	{ 28,  "CREATE_NEW_TREE",                   { kTypeNumber, kTypeVector, kTypeNumber, kTypeNumber, kTypeFloat, kTypeFloat, kTypeFloat },                            &Functions::createNewTree },
	{ 29,  "CREATE_FIELD",                      { kTypeVector, kTypeNumber },                                                                                          &Functions::createField },
	{ 30,  "CREATE_TOWN_FIELD",                 { kTypeNumber, kTypeVector, kTypeNumber },                                                                             &Functions::createTownField },
	{ 31,  "CREATE_FISH_FARM",                  { kTypeVector, kTypeNumber },                                                                                          &Functions::createFishFarm },
	{ 32,  "CREATE_TOWN_FISH_FARM",             { kTypeNumber, kTypeVector, kTypeNumber },                                                                             &Functions::createTownFishFarm },
	{ 33,  "CREATE_FEATURE",                    { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createFeature },
	{ 34,  "CREATE_FLOWERS",                    { kTypeVector, kTypeNumber, kTypeFloat, kTypeFloat },                                                                  &Functions::createFlowers },
	{ 35,  "CREATE_WALL_SECTION",               { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createWallSection },
	{ 36,  "CREATE_PLANNED_WALL_SECTION",       { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createPlannedWallSection },
	{ 37,  "CREATE_PITCH",                      { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber, kTypeNumber },                                      &Functions::createPitch },
	{ 38,  "CREATE_POT",                        { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                                                &Functions::createPot },
	{ 39,  "CREATE_TOWN_TEMPORARY_POTS",        { kTypeNumber, kTypeNumber, kTypeNumber },                                                                             &Functions::createTownTemporaryPots },
	{ 40,  "CREATE_MOBILEOBJECT",               { kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                                                &Functions::createMobileobject },
	{ 41,  "CREATE_MOBILESTATIC",               { kTypeVector, kTypeNumber, kTypeFloat, kTypeFloat },                                                                  &Functions::createMobilestatic },
	{ 42,  "CREATE_MOBILE_STATIC",              { kTypeVector, kTypeNumber, kTypeFloat, kTypeFloat, kTypeFloat, kTypeFloat, kTypeFloat },                              &Functions::createMobileStatic },
	{ 43,  "CREATE_DEAD_TREE",                  { kTypeVector, kTypeString, kTypeNumber, kTypeFloat, kTypeFloat, kTypeFloat, kTypeFloat },                             &Functions::createDeadTree },
	{ 44,  "CREATE_SCAFFOLD",                   { kTypeNumber, kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createScaffold },
	{ 45,  "COUNTRY_CHANGE",                    { kTypeVector, kTypeNumber },                                                                                          &Functions::countryChange },
	{ 46,  "HEIGHT_CHANGE",                     { kTypeVector, kTypeNumber },                                                                                          &Functions::heightChange },
	{ 47,  "CREATE_CREATURE",                   { kTypeVector, kTypeNumber, kTypeNumber },                                                                             &Functions::createCreature },
	{ 48,  "CREATE_CREATURE_FROM_FILE",         { kTypeString, kTypeNumber, kTypeVector, kTypeVector },                                                                &Functions::createCreatureFromFile },
	{ 49,  "CREATE_FLOCK",                      { kTypeNumber, kTypeVector, kTypeVector, kTypeNumber, kTypeNumber, kTypeNumber },                                      &Functions::createFlock },
	{ 50,  "LOAD_LANDSCAPE",                    { kTypeString },                                                                                                       &Functions::loadLandscape },
	{ 51,  "VERSION",                           { kTypeFloat },                                                                                                        &Functions::version },
	{ 52,  "CREATE_AREA",                       { kTypeVector, kTypeFloat },                                                                                           &Functions::createArea },
	{ 53,  "START_CAMERA_POS",                  { kTypeVector },                                                                                                       &Functions::startCameraPos },
	{ 54,  "FLY_BY_FILE",                       { kTypeString },                                                                                                       &Functions::flyByFile },
	{ 55,  "TOWN_NEEDS_POS",                    { kTypeNumber, kTypeVector },                                                                                          &Functions::townNeedsPos },
	{ 56,  "CREATE_FURNITURE",                  { kTypeVector, kTypeNumber, kTypeFloat },                                                                              &Functions::createFurniture },
	{ 57,  "CREATE_BIG_FOREST",                 { kTypeVector, kTypeNumber, kTypeFloat, kTypeFloat },                                                                  &Functions::createBigForest },
	{ 58,  "CREATE_NEW_BIG_FOREST",             { kTypeVector, kTypeNumber, kTypeNumber, kTypeFloat, kTypeFloat },                                                     &Functions::createNewBigForest },
	{ 59,  "CREATE_INFLUENCE_RING",             { kTypeVector, kTypeNumber, kTypeFloat, kTypeNumber },                                                                 &Functions::createInfluenceRing },
	{ 60,  "CREATE_WEATHER_CLIMATE",            { kTypeNumber, kTypeNumber, kTypeVector, kTypeFloat, kTypeFloat },                                                     &Functions::createWeatherClimate },
	{ 61,  "CREATE_WEATHER_CLIMATE_RAIN",       { kTypeNumber, kTypeFloat, kTypeNumber, kTypeNumber, kTypeNumber },                                                    &Functions::createWeatherClimateRain },
	{ 62,  "CREATE_WEATHER_CLIMATE_TEMP",       { kTypeNumber, kTypeFloat, kTypeFloat },                                                                               &Functions::createWeatherClimateTemp },
	{ 63,  "CREATE_WEATHER_CLIMATE_WIND",       { kTypeNumber, kTypeFloat, kTypeFloat, kTypeFloat },                                                                   &Functions::createWeatherClimateWind },
	{ 64,  "CREATE_WEATHER_STORM",              { kTypeNumber, kTypeVector, kTypeFloat, kTypeNumber, kTypeVector, kTypeVector, kTypeVector, kTypeFloat, kTypeVector }, &Functions::createWeatherStorm },
	{ 65,  "BRUSH_SIZE",                        { kTypeFloat, kTypeFloat },                                                                                            &Functions::brushSize },
	{ 66,  "CREATE_STREAM",                     { kTypeNumber },                                                                                                       &Functions::createStream },
	{ 67,  "CREATE_STREAM_POINT",               { kTypeNumber, kTypeVector },                                                                                          &Functions::createStreamPoint },
	{ 68,  "CREATE_WATERFALL",                  { kTypeVector },                                                                                                       &Functions::createWaterfall },
	{ 69,  "CREATE_ARENA",                      { kTypeVector, kTypeFloat },                                                                                           &Functions::createArena },
	{ 70,  "CREATE_FOOTPATH",                   { kTypeNumber },                                                                                                       &Functions::createFootpath },
	{ 71,  "CREATE_FOOTPATH_NODE",              { kTypeNumber, kTypeVector },                                                                                          &Functions::createFootpathNode },
	{ 72,  "LINK_FOOTPATH",                     { kTypeNumber },                                                                                                       &Functions::linkFootpath },
	{ 73,  "CREATE_BONFIRE",                    { kTypeVector, kTypeFloat, kTypeFloat, kTypeFloat },                                                                   &Functions::createBonfire },
	{ 74,  "CREATE_BASE",                       { kTypeVector, kTypeNumber },                                                                                          &Functions::createBase },
	{ 75,  "CREATE_NEW_FEATURE",                { kTypeVector, kTypeString, kTypeNumber, kTypeNumber, kTypeNumber },                                                   &Functions::createNewFeature },
	{ 76,  "SET_INTERACT_DESIRE",               { kTypeFloat },                                                                                                        &Functions::setInteractDesire },
	{ 77,  "TOGGLE_COMPUTER_PLAYER",            { kTypeString, kTypeNumber },                                                                                          &Functions::toggleComputerPlayer },
	{ 78,  "SET_COMPUTER_PLAYER_CREATURE_LIKE", { kTypeString, kTypeString },                                                                                          &Functions::setComputerPlayerCreatureLike },
	{ 79,  "MULTIPLAYER_DEBUG",                 { kTypeNumber, kTypeNumber },                                                                                          &Functions::multiplayerDebug },
	{ 80,  "CREATE_STREET_LANTERN",             { kTypeVector, kTypeNumber },                                                                                          &Functions::createStreetLantern },
	{ 81,  "CREATE_STREET_LIGHT",               { kTypeVector },                                                                                                       &Functions::createStreetLight },
	{ 82,  "SET_LAND_NUMBER",                   { kTypeNumber },                                                                                                       &Functions::setLandNumber },
	{ 83,  "CREATE_ONE_SHOT_SPELL",             { kTypeVector, kTypeString },                                                                                          &Functions::createOneShotSpell },
	{ 84,  "CREATE_ONE_SHOT_SPELL_PU",          { kTypeVector, kTypeString },                                                                                          &Functions::createOneShotSpellPu },
	{ 85,  "CREATE_FIRE_FLY",                   { kTypeVector },                                                                                                       &Functions::createFireFly },
	{ 86,  "TOWN_DESIRE_BOOST",                 { kTypeNumber, kTypeString, kTypeFloat },                                                                              &Functions::townDesireBoost },
	{ 87,  "CREATE_ANIMATED_STATIC",            { kTypeVector, kTypeString, kTypeNumber, kTypeNumber },                                                                &Functions::createAnimatedStatic },
	{ 88,  "FIRE_FLY_SPELL_REWARD_PROB",        { kTypeVector, kTypeFloat },                                                                                           &Functions::fireFlySpellRewardProb },
	{ 89,  "CREATE_NEW_TOWN_FIELD",             { kTypeNumber, kTypeVector, kTypeNumber, kTypeFloat },                                                                 &Functions::createNewTownField },
	{ 90,  "CREATE_SPELL_DISPENSER",            { kTypeNumber, kTypeVector, kTypeString, kTypeString, kTypeFloat, kTypeFloat, kTypeFloat },                            &Functions::createSpellDispenser },
	{ 91,  "LOAD_COMPUTER_PLAYER_PERSONALLTY",  { kTypeNumber, kTypeVector },                                                                                          &Functions::loadComputerPlayerPersonallty },
	{ 92,  "SET_COMPUTER_PLAYER_PERSONALLTY",   { kTypeString, kTypeVector, kTypeFloat },                                                                              &Functions::setComputerPlayerPersonallty },
	{ 93,  "SET_GLOBAL_LAND_BALANCE",           { kTypeNumber, kTypeFloat },                                                                                           &Functions::setGlobalLandBalance },
	{ 94,  "SET_LAND_BALANCE",                  { kTypeString, kTypeNumber, kTypeFloat },                                                                              &Functions::setLandBalance },
	{ 95,  "CREATE_DRINK_WAYPOINT",             { kTypeVector },                                                                                                       &Functions::createDrinkWaypoint },
	{ 96,  "SET_TOWN_INFLUENCE_MULTIPLIER",     { kTypeFloat },                                                                                                        &Functions::setTownInfluenceMultiplier },
	{ 97,  "SET_PLAYER_INFLUENCE_MULTIPLIER",   { kTypeFloat },                                                                                                        &Functions::setPlayerInfluenceMultiplier },
	{ 98,  "SET_TOWN_BALANCE_BELIEF_SCALE",     { kTypeNumber, kTypeFloat },                                                                                           &Functions::setTownBalanceBeliefScale },
	{ 99,  "START_GAME_MESSAGE",                { kTypeVector, kTypeNumber },                                                                                          &Functions::startGameMessage },
	{ 100, "ADD_GAME_MESSAGE_LINE",             { kTypeVector, kTypeNumber },                                                                                          &Functions::addGameMessageLine },
	{ 101, "EDIT_LEVEL",                        {  },                                                                                                                  &Functions::editLevel },
	{ 102, "SET_NIGHTTIME",                     { kTypeFloat, kTypeFloat, kTypeFloat },                                                                                &Functions::setNighttime },
	{ 103, "MAKE_LAST_OBJECT_ARTIFACT",         { kTypeNumber, kTypeString, kTypeFloat },                                                                              &Functions::makeLastObjectArtifact },
	{ 104, "SET_LOST_TOWN_SCALE",               { kTypeFloat },                                                                                                        &Functions::setLostTownScale },
};
