/*****************************************************************************
 * Copyright (c) 2018-2020 openblack developers
 *
 * For a complete list of all authors, please refer to contributors.md
 * Interested in contributing? Visit https://github.com/openblack/openblack
 *
 * openblack is licensed under the GNU General Public License version 3.
 *****************************************************************************/

#include "MeshLookup.h"

using namespace openblack;

MeshLookup<TreeInfo> openblack::treeMeshLookup {
    {TreeInfo::Beech, MeshPackId::TreeBeech},       {TreeInfo::Birch, MeshPackId::TreeBirch},
    {TreeInfo::Cedar, MeshPackId::TreeCedar},       {TreeInfo::Conifer, MeshPackId::TreeConifer},
    {TreeInfo::ConiferA, MeshPackId::TreeConiferA}, {TreeInfo::Oak, MeshPackId::TreeOak},
    {TreeInfo::OakA, MeshPackId::TreeOakA},         {TreeInfo::Olive, MeshPackId::TreeOlive},
    {TreeInfo::Palm, MeshPackId::TreePalm},         {TreeInfo::PalmA, MeshPackId::TreePalmA},
    {TreeInfo::PalmB, MeshPackId::TreePalmB},       {TreeInfo::PalmC, MeshPackId::TreePalmC},
    {TreeInfo::Pine, MeshPackId::TreePine},         {TreeInfo::Bush, MeshPackId::TreeBush},
    {TreeInfo::BushA, MeshPackId::TreeBushA},       {TreeInfo::BushB, MeshPackId::TreeBushB},
    {TreeInfo::Cypress, MeshPackId::TreeCypress},   {TreeInfo::CypressA, MeshPackId::TreeCypressA},
    {TreeInfo::Copse, MeshPackId::TreeCopse},       {TreeInfo::CopseA, MeshPackId::TreeCopseA},
    {TreeInfo::Hedge, MeshPackId::TreeHedge},       {TreeInfo::HedgeA, MeshPackId::TreeHedgeA},
    {TreeInfo::Burnt, MeshPackId::ObjectBurntTree}};

MeshLookup<AbodeInfo> openblack::abodeMeshLookup {// Norse
                                                  {AbodeInfo::NorseTownCentre, MeshPackId::BuildingNorseVillageCentre},
                                                  {AbodeInfo::NorseStoragePit, MeshPackId::BuildingNorseStoragePit},
                                                  {AbodeInfo::NorseGraveyard, MeshPackId::BuildingNorseGraveyard},
                                                  {AbodeInfo::NorseWorkshop, MeshPackId::BuildingNorseWorkshop},
                                                  {AbodeInfo::NorseCreche, MeshPackId::BuildingNorseCreche},
                                                  {AbodeInfo::NorseHut, MeshPackId::BuildingNorse1},
                                                  {AbodeInfo::NorseShackX, MeshPackId::BuildingNorse2},
                                                  {AbodeInfo::NorseShackY, MeshPackId::BuildingNorse3},
                                                  {AbodeInfo::NorseTent, MeshPackId::BuildingNorse4},
                                                  {AbodeInfo::NorseTempleX, MeshPackId::BuildingNorse5},
                                                  {AbodeInfo::NorseTempleY, MeshPackId::BuildingNorse2A},
                                                  {AbodeInfo::NorseWonder, MeshPackId::BuildingNorseWonder},
                                                  // Celtic
                                                  {AbodeInfo::CelticTownCentre, MeshPackId::BuildingCelticVillageCentre},
                                                  {AbodeInfo::CelticStoragePit, MeshPackId::BuildingCelticStoragePit},
                                                  {AbodeInfo::CelticGraveyard, MeshPackId::BuildingCelticGraveyard},
                                                  {AbodeInfo::CelticWorkshop, MeshPackId::BuildingCelticWorkshop},
                                                  {AbodeInfo::CelticCreche, MeshPackId::BuildingCelticCreche},
                                                  {AbodeInfo::CelticHut, MeshPackId::BuildingCeltic1},
                                                  {AbodeInfo::CelticShackX, MeshPackId::BuildingCeltic2},
                                                  {AbodeInfo::CelticShackY, MeshPackId::BuildingCeltic3},
                                                  {AbodeInfo::CelticTent, MeshPackId::BuildingCeltic4},
                                                  {AbodeInfo::CelticTempleX, MeshPackId::BuildingCeltic5},
                                                  {AbodeInfo::CelticWonder, MeshPackId::BuildingCelticWonder},
                                                  // Japanese
                                                  {AbodeInfo::JapaneseTownCentre, MeshPackId::BuildingJapaneseVillageCentre},
                                                  {AbodeInfo::JapaneseStoragePit, MeshPackId::BuildingJapaneseStoragePit},
                                                  {AbodeInfo::JapaneseGraveyard, MeshPackId::BuildingJapaneseGraveyard},
                                                  {AbodeInfo::JapaneseWorkshop, MeshPackId::BuildingJapaneseWorkshop},
                                                  {AbodeInfo::JapaneseCreche, MeshPackId::BuildingJapaneseCreche},
                                                  {AbodeInfo::JapaneseHut, MeshPackId::BuildingJapanese1},
                                                  {AbodeInfo::JapaneseShackX, MeshPackId::BuildingJapanese2},
                                                  {AbodeInfo::JapaneseShackY, MeshPackId::BuildingJapanese3},
                                                  {AbodeInfo::JapaneseTent, MeshPackId::BuildingJapanese4},
                                                  {AbodeInfo::JapaneseTempleX, MeshPackId::BuildingJapanese5},
                                                  {AbodeInfo::JapaneseWonder, MeshPackId::BuildingJapaneseWonder},
                                                  // Aztec
                                                  {AbodeInfo::AztecTownCentre, MeshPackId::BuildingAztecVillageCentre},
                                                  {AbodeInfo::AztecStoragePit, MeshPackId::BuildingAztecStoragePit},
                                                  {AbodeInfo::AztecGraveyard, MeshPackId::BuildingAztecGraveyard},
                                                  {AbodeInfo::AztecWorkshop, MeshPackId::BuildingAztecWorkshop},
                                                  {AbodeInfo::AztecCreche, MeshPackId::BuildingAztecCreche},
                                                  {AbodeInfo::AztecHut, MeshPackId::BuildingAztec1},
                                                  {AbodeInfo::AztecShackX, MeshPackId::BuildingAztec2},
                                                  {AbodeInfo::AztecShackY, MeshPackId::BuildingAztec3},
                                                  {AbodeInfo::AztecTent, MeshPackId::BuildingAztec4},
                                                  {AbodeInfo::AztecTempleX, MeshPackId::BuildingAztec5},
                                                  {AbodeInfo::AztecWonder, MeshPackId::BuildingAztecWonder},
                                                  // Tibetan
                                                  {AbodeInfo::TibetanTownCentre, MeshPackId::BuildingTibetanVillageCentre},
                                                  {AbodeInfo::TibetanStoragePit, MeshPackId::BuildingTibetanStoragePit},
                                                  {AbodeInfo::TibetanGraveyard, MeshPackId::BuildingTibetanGraveyard},
                                                  {AbodeInfo::TibetanWonder, MeshPackId::BuildingTibetanWorkshop},
                                                  {AbodeInfo::TibetanCreche, MeshPackId::BuildingTibetanCreche},
                                                  {AbodeInfo::TibetanHut, MeshPackId::BuildingTibetan1},
                                                  {AbodeInfo::TibetanShackX, MeshPackId::BuildingTibetan2},
                                                  {AbodeInfo::TibetanShackY, MeshPackId::BuildingTibetan3},
                                                  {AbodeInfo::TibetanTent, MeshPackId::BuildingTibetan4},
                                                  {AbodeInfo::TibetanTempleX, MeshPackId::BuildingTibetan5},
                                                  {AbodeInfo::TibetanWonder, MeshPackId::BuildingTibetanWonder},
                                                  // Indian
                                                  {AbodeInfo::IndianTownCentre, MeshPackId::BuildingAmericanVillageCentre},
                                                  {AbodeInfo::IndianStoragePit, MeshPackId::BuildingAmericanStoragePit},
                                                  {AbodeInfo::IndianGraveyard, MeshPackId::BuildingAmericanGraveyard},
                                                  {AbodeInfo::IndianWorkshop, MeshPackId::BuildingAmericanWorkshop},
                                                  {AbodeInfo::IndianCreche, MeshPackId::BuildingAmericanCreche},
                                                  {AbodeInfo::IndianHut, MeshPackId::BuildingAmerican1},
                                                  {AbodeInfo::IndianShackX, MeshPackId::BuildingAmerican2},
                                                  {AbodeInfo::IndianShackY, MeshPackId::BuildingAmerican3},
                                                  {AbodeInfo::IndianTent, MeshPackId::BuildingAmerican4},
                                                  {AbodeInfo::IndianTempleX, MeshPackId::BuildingAmerican5},
                                                  {AbodeInfo::IndianWonder, MeshPackId::BuildingAmericanWonder},
                                                  // Greek
                                                  {AbodeInfo::GreekTownCentre, MeshPackId::BuildingGreekVillageCentre},
                                                  {AbodeInfo::GreekStoragePit, MeshPackId::BuildingGreekStoragePit},
                                                  {AbodeInfo::GreekGraveyard, MeshPackId::BuildingGreekGraveyard},
                                                  {AbodeInfo::GreekWorkshop, MeshPackId::BuildingGreekWorkshop},
                                                  {AbodeInfo::GreekCreche, MeshPackId::BuildingGreekCreche},
                                                  {AbodeInfo::GreekHut, MeshPackId::BuildingGreek1},
                                                  {AbodeInfo::GreekShackX, MeshPackId::BuildingGreek2},
                                                  {AbodeInfo::GreekShackY, MeshPackId::BuildingGreek3},
                                                  {AbodeInfo::GreekTent, MeshPackId::BuildingGreek4},
                                                  {AbodeInfo::GreekTempleX, MeshPackId::BuildingGreek5},
                                                  {AbodeInfo::GreekTempleY, MeshPackId::BuildingGreek5A},
                                                  {AbodeInfo::GreekWonder, MeshPackId::BuildingGreekWonder}};

MeshLookup<VillagerType, VillagerTypeId> openblack::villagerMeshLookup {
    {{VillageEthnicities::AZTEC, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonAztecMaleA1},
    {{VillageEthnicities::AZTEC, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonAztecFemaleA1},
    {{VillageEthnicities::AZTEC, VillagerLifeStage::Child, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonBoyTan1},
    {{VillageEthnicities::AZTEC, VillagerLifeStage::Child, VillagerSex::FEMALE, VillagerRoles::NONE}, MeshPackId::PersonGirlTan1},
    {{VillageEthnicities::CELTIC, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonCelticMaleA1},
    {{VillageEthnicities::CELTIC, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonCelticFemaleA1},
    {{VillageEthnicities::CELTIC, VillagerLifeStage::Child, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonBoyWhite},
    {{VillageEthnicities::CELTIC, VillagerLifeStage::Child, VillagerSex::FEMALE, VillagerRoles::NONE}, MeshPackId::PersonGirlWhite},
    {{VillageEthnicities::EGYPTIAN, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonEgyptianMaleA1},
    {{VillageEthnicities::EGYPTIAN, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonEgyptianFemaleA1},
    {{VillageEthnicities::GREEK, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonGreekMaleA1},
    {{VillageEthnicities::GREEK, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonGreekFemaleA1},
    {{VillageEthnicities::INDIAN, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonAmericanMaleA1},
    {{VillageEthnicities::INDIAN, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonAmericanFemaleA1},
    {{VillageEthnicities::JAPANESE, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonJapaneseMaleA1},
    {{VillageEthnicities::JAPANESE, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonJapaneseFemaleA2},
    {{VillageEthnicities::NORSE, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonNorseMaleA1},
    {{VillageEthnicities::NORSE, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonNorseFemaleA1},
    {{VillageEthnicities::NORSE, VillagerLifeStage::Child, VillagerSex::MALE, VillagerRoles::NONE}, MeshPackId::PersonBoyWhite},
    {{VillageEthnicities::NORSE, VillagerLifeStage::Child, VillagerSex::FEMALE, VillagerRoles::NONE}, MeshPackId::PersonGirlWhite},
    {{VillageEthnicities::TIBETAN, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonTibetanMaleA1},
    {{VillageEthnicities::TIBETAN, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonTibetanFemaleA2},
    {{VillageEthnicities::AFRICAN, VillagerLifeStage::Adult, VillagerSex::MALE, VillagerRoles::NONE},
     MeshPackId::PersonEgyptianMaleA1},
    {{VillageEthnicities::AFRICAN, VillagerLifeStage::Adult, VillagerSex::FEMALE, VillagerRoles::NONE},
     MeshPackId::PersonEgyptianFemaleA1}};

MeshLookup<MobileStaticInfo> openblack::mobileStaticMeshLookup {
    {MobileStaticInfo::Rock, MeshPackId::ObjectFlatRockChalk},
    {MobileStaticInfo::Bonfire, MeshPackId::BuildingCampfire},
    {MobileStaticInfo::Boulder1Chalk, MeshPackId::Boulder1Chalk},
    {MobileStaticInfo::Boulder1Lime, MeshPackId::Boulder1Lime},
    {MobileStaticInfo::Boulder1Sand, MeshPackId::Boulder1Sand},
    {MobileStaticInfo::Boulder1Volcanic, MeshPackId::Boulder1Volcanic},
    {MobileStaticInfo::Boulder2Chalk, MeshPackId::Boulder2Chalk},
    {MobileStaticInfo::Boulder2Lime, MeshPackId::Boulder2Lime},
    {MobileStaticInfo::Boulder2Sand, MeshPackId::Boulder2Sand},
    {MobileStaticInfo::Boulder2Volcanic, MeshPackId::Boulder2Volcanic},
    {MobileStaticInfo::Boulder3Chalk, MeshPackId::Boulder3Chalk},
    {MobileStaticInfo::Boulder3Lime, MeshPackId::Boulder3Lime},
    {MobileStaticInfo::Boulder3Sand, MeshPackId::Boulder3Sand},
    {MobileStaticInfo::Boulder3Volcanic, MeshPackId::Boulder3Volcanic},
    {MobileStaticInfo::CeltFenceShort, MeshPackId::BuildingCelticFenceShort},
    {MobileStaticInfo::CeltFenceTall, MeshPackId::BuildingCelticFenceTall},
    {MobileStaticInfo::CountryLantern, MeshPackId::ObjectTownLight},
    {MobileStaticInfo::DeadTree, MeshPackId::ObjectBurntTree},
    {MobileStaticInfo::ToyBall, MeshPackId::ObjectToyBall},
    {MobileStaticInfo::Idol, MeshPackId::FeatureIdol},
    {MobileStaticInfo::ToyDie, MeshPackId::ObjectToyDice},
    {MobileStaticInfo::ToyCuddly, MeshPackId::ObjectToyCuddly},
    {MobileStaticInfo::ToySkittle, MeshPackId::ObjectToySkittle},
    {MobileStaticInfo::Vortex, MeshPackId::SpellVortexCylinder},
    {MobileStaticInfo::GateTotemApe, MeshPackId::ObjectGateTotemApe},
    {MobileStaticInfo::GateTotemCow, MeshPackId::ObjectGateTotemCow},
    {MobileStaticInfo::GateTotemTiger, MeshPackId::ObjectGateTotemTiger},
    {MobileStaticInfo::GateTotemBlank, MeshPackId::ObjectGateTotemBlank},
    {MobileStaticInfo::LongrockChalk, MeshPackId::ObjectLongRockChalk},
    {MobileStaticInfo::LongrockLimestone, MeshPackId::ObjectLongRockLimeStone},
    {MobileStaticInfo::LongrockSandstone, MeshPackId::ObjectLongRockSandStone},
    {MobileStaticInfo::LongrockVolcanic, MeshPackId::ObjectLongRockVolcanic},
    {MobileStaticInfo::RockChalk, MeshPackId::ObjectRockChalk},
    {MobileStaticInfo::RockLimestone, MeshPackId::ObjectRockLimeStone},
    {MobileStaticInfo::RockSandstone, MeshPackId::ObjectRockSandStone},
    {MobileStaticInfo::RockVolcanic, MeshPackId::ObjectRockVolcanic},
    {MobileStaticInfo::SharprockChalk, MeshPackId::ObjectSharpRockChalk},
    {MobileStaticInfo::SharprockLimestone, MeshPackId::ObjectSharpRockLimeStone},
    {MobileStaticInfo::SharprockSandstone, MeshPackId::ObjectSharpRockSandStone},
    {MobileStaticInfo::SharprockVolcanic, MeshPackId::ObjectSharpRockVolcanic}};

MeshLookup<MobileObjectInfo> openblack::mobileObjectMeshLookup {
    {MobileObjectInfo::EgyptBarrel, MeshPackId::BuildingEgyptianBarrel},
    {MobileObjectInfo::EgyptCart, MeshPackId::BuildingEgyptianCart},
    {MobileObjectInfo::EgyptPotA, MeshPackId::BuildingEgyptianPotA},
    {MobileObjectInfo::EgyptPotB, MeshPackId::BuildingEgyptianPotB},
    {MobileObjectInfo::MagicFood, MeshPackId::Dummy},
    {MobileObjectInfo::LumpOfPoo, MeshPackId::ObjectCreatureTurd},
    {MobileObjectInfo::WaterJug, MeshPackId::Dummy},
    {MobileObjectInfo::Arrow, MeshPackId::Dummy},
    {MobileObjectInfo::Ball, MeshPackId::Dummy},
    {MobileObjectInfo::Cart, MeshPackId::BuildingEgyptianCart},
    {MobileObjectInfo::FoodPot, MeshPackId::BuildingEgyptianPotA},
    {MobileObjectInfo::WoodPot, MeshPackId::BuildingEgyptianPotA},
    {MobileObjectInfo::PileFood, MeshPackId::BuildingEgyptianPotA},
    {MobileObjectInfo::PileWood, MeshPackId::BuildingEgyptianPotA},
    {MobileObjectInfo::MagicWood, MeshPackId::BuildingWood00},
    {MobileObjectInfo::Crop, MeshPackId::TreeBush},
    {MobileObjectInfo::OldScaffold, MeshPackId::Dummy},
    {MobileObjectInfo::Champi, MeshPackId::ObjectChampi},
    {MobileObjectInfo::Toadstool, MeshPackId::ObjectToadstool},
    {MobileObjectInfo::MagicMushroom, MeshPackId::ObjectMagicMushroom},
    {MobileObjectInfo::CreatureSwapOrb, MeshPackId::Dummy},
    {MobileObjectInfo::Creed, MeshPackId::Creed},
    {MobileObjectInfo::Eyes, MeshPackId::Creed},
    {MobileObjectInfo::Ark, MeshPackId::ObjectArk},
    {MobileObjectInfo::Whale, MeshPackId::ObjectLargeFishDead},
    {MobileObjectInfo::OneOffSpellSeed, MeshPackId::Dummy},
    {MobileObjectInfo::HanoiPuzzleBase, MeshPackId::BuildingXandoBase},
    {MobileObjectInfo::HanoiPuzzlePart1, MeshPackId::Puzzle1},
    {MobileObjectInfo::HanoiPuzzlePart2, MeshPackId::Puzzle2},
    {MobileObjectInfo::HanoiPuzzlePart3, MeshPackId::Puzzle3},
    {MobileObjectInfo::HanoiPuzzlePart4, MeshPackId::Puzzle4},
};

MeshLookup<FeatureInfo> openblack::featureMeshLookup {{FeatureInfo::FatPilarSand, MeshPackId::FatPilarSand},
                                                      {FeatureInfo::Pilar2Sand, MeshPackId::Pilar2Sand},
                                                      {FeatureInfo::Pilar3Sand, MeshPackId::Pilar3Sand},
                                                      {FeatureInfo::FatPilarChalk, MeshPackId::FatPilarChalk},
                                                      {FeatureInfo::Pilar2Chalk, MeshPackId::Pilar2Chalk},
                                                      {FeatureInfo::Pilar3Chalk, MeshPackId::Pilar3Chalk},
                                                      {FeatureInfo::FatPilarLime, MeshPackId::FatPilarLime},
                                                      {FeatureInfo::Pilar2Lime, MeshPackId::Pilar2Lime},
                                                      {FeatureInfo::Pilar3Lime, MeshPackId::Pilar3Lime},
                                                      {FeatureInfo::PilarVolcanic, MeshPackId::PilarVolcanic},
                                                      {FeatureInfo::Pilar2Volcanic, MeshPackId::Pilar2Volcanic},
                                                      {FeatureInfo::Pilar3Volcanic, MeshPackId::Pilar3Volcanic},
                                                      {FeatureInfo::Ark, MeshPackId::ObjectArk},
                                                      {FeatureInfo::ArkWreck, MeshPackId::ObjectArkWreck},
                                                      {FeatureInfo::ArkDryDock, MeshPackId::ObjectArkDryDock},
                                                      {FeatureInfo::MagicMushroom, MeshPackId::ObjectMagicMushroom},
                                                      {FeatureInfo::Toadstool, MeshPackId::ObjectToadstool},
                                                      {FeatureInfo::AztcStatue, MeshPackId::BuildingAztecStatue},
                                                      {FeatureInfo::SpikeyPilarLime, MeshPackId::SpikeyPilarLime},
                                                      {FeatureInfo::SpikeyPilarChalk, MeshPackId::SpikeyPilarChalk},
                                                      {FeatureInfo::SpikeyPilarSand, MeshPackId::SpikeyPilarSand},
                                                      {FeatureInfo::SpikeyPilarVolcanic, MeshPackId::SpikeyPilarVolcanic}};
