name: Formatting Check
on:
  pull_request:
  push:
    tags:
    branches:
      - 'master'
jobs:
  formatting-check:
    name: clang-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'src apps components'
          clangFormatVersion: 12
          inplace: False

  # Run only if a PR and clang-format has failed
  formatting-action-suggester:
    name: clang-format fix suggester
    needs: formatting-check
    if: always() && github.event_name == 'pull_request' && needs.formatting-check.result == 'failure'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DoozyX/clang-format-lint-action@v0.13
        with:
          source: 'src apps components'
          clangFormatVersion: 12
          inplace: True
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: clang-format

      - run: |
          git diff > format.patch

      - uses: actions/upload-artifact@v2
        with:
          name: formatting-fix
          path: format.patch
