steps:
 - bash: |
     cmake --install build -v --prefix install --config ${{ parameters.BuildConfiguration }}
   displayName: 'Install'
 - publish: $(System.DefaultWorkingDirectory)/install
   artifact: openblack-${{ parameters.InstallPlatform }}-${{ parameters.BuildConfiguration }}-$(Build.SourceVersion)
